name: Build and release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Run Maven release
 #       run: ./release.sh
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}